print('Content-type:text/html \n\n')
print('<html>')
print('<head>')
print('<meta charset="utf-8">')
print('<title>Hello World</title>')
print('</head>')
print('<body>')
print('<h2>Hello World!</h2>')
print('</body>')
print('</html>')